version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: npm-check-updates
    versions:
    - 11.1.9
    - 11.3.0
    - 11.4.1
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.14
    - 6.1.16
    - 6.1.18
    - 6.1.20
    - 6.2.1
    - 6.2.8
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.9
  - dependency-name: "@ant-design/icons"
    versions:
    - 4.5.0
  - dependency-name: boclips-player
    versions:
    - 6.3.3
  - dependency-name: boclips-api-client
    versions:
    - 25.0.1
    - 30.0.0
    - 31.0.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.1.14
    - 6.1.17
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
