---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cypress/base
    tag: '10'

inputs:
- name: source

outputs:
- name: dist

run:
  path: pipeline/scripts/build.sh
  dir: source

caches:
  - path: ../../../../root/.cache
  - path: ../../../../root/.npm
