---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: '10'

inputs:
- name: source

outputs:
- name: dist

run:
  path: pipeline/scripts/build.sh
  dir: source