---
jobs:
- name: build
  plan:
  - get: source
    trigger: true
  - put: version
    params:
      bump: minor
  - task: build
    file: source/pipeline/tasks/build.yml
  - put: container-registry
    params:
      build: dist
      additional_tags: version/version
      tag_as_latest: true

- name: deploy-staging
  plan:
  - get: version
    passed: [build]
    trigger: true
  - get: source
    passed: [build]
  - get: infrastructure
  - task: render-manifests
    file: infrastructure/concourse/tasks/render-manifests.yml
    input_mapping:
      source: source
    params:
      DOMAIN: staging-boclips.com
      INPUT_MANIFESTS_DIR: source/k8s
      REPLICAS: 1
  - put: staging
    params:
      kubectl: apply -f rendered_manifests/all.yaml
      wait_until_ready_selector: app=teachers-ui

- name: deploy-production
  plan:
  - get: version
    passed: [deploy-staging]
  - get: source
    passed: [deploy-staging]
  - get: infrastructure
  - task: render-manifests
    file: infrastructure/concourse/tasks/render-manifests.yml
    input_mapping:
      source: source
    params:
      DOMAIN: boclips.com
      INPUT_MANIFESTS_DIR: source/k8s
      REPLICAS: 1
  - put: production
    params:
      kubectl: apply -f rendered_manifests/all.yaml
      wait_until_ready_selector: app=teachers-ui

resources:
- name: source
  type: git
  source:
    branch: master
    private_key: {{private-key}}
    uri: git@github.com:knowledgemotion/teachers-ui.git

- name: staging
  type: kubernetes
  source:
    server: {{kubernetes-server}}
    namespace: staging
    token: {{kubernetes-staging-token}}
    certificate_authority: {{kubernetes-staging-ca}}

- name: production
  type: kubernetes
  source:
    server: {{kubernetes-server}}
    namespace: production
    token: {{kubernetes-production-token}}
    certificate_authority: {{kubernetes-production-ca}}

- name: version
  type: semver
  source:
    initial_version: "0.167.0"
    driver: git
    uri: git@github.com:knowledgemotion/versions.git
    branch: master
    file: teachers-ui
    private_key: {{versions-repo-key}}

- name: container-registry
  type: docker-image
  source:
    repository: eu.gcr.io/boclips-prod/boclips/teachers-ui
    username: _json_key
    password: {{gcr-key}}

- name: infrastructure
  type: git
  source:
    branch: master
    private_key: {{infrastructure-repo-key}}
    uri: git@github.com:knowledgemotion/infrastructure.git

resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.11"
