enum EventTypes {
  ACTIVATION_COMPLETE = 'ACTIVATION_COMPLETE',
  VIDEO_SEARCH = 'VIDEO_SEARCH',
  VIDEO_VISITED = 'VIDEO_VISITED',
  VIDEO_LINK_COPIED = 'VIDEO_LINK_COPIED',
  VIDEO_ADDED_TO_COLLECTION = 'COLLECTION_VIDEO_ADDED',
  VIDEO_REMOVED_FROM_COLLECTION = 'COLLECTION_VIDEO_REMOVED',
  DEFAULT_COLLECTION_VISITED = 'COLLECTION_VISITED',
  COLLECTION_CREATED = 'COLLECTION_CREATED',
  COLLECTION_RENAMED = 'COLLECTION_RENAMED',
  COLLECTION_REMOVED = 'COLLECTION_REMOVED',
  MY_COLLECTIONS_VISITED = 'MY_COLLECTIONS_VISITED',
  VIDEO_PLAYBACK = 'VIDEO_PLAYBACK',
  VISIBILITY_CHANGED = 'VISIBILITY_CHANGED',
  REGISTRATION_INITIATED = 'REGISTRATION_INITIATED',
  COLLECTION_BOOKMARKED = 'COLLECTION_BOOKMARKED',
  COLLECTION_UNBOOKMARKED = 'COLLECTION_UNBOOKMARKED',
  REGISTRATION_ATTEMPT_FAILED = 'REGISTRATION_ATTEMPT_FAILED',
}

export default EventTypes;
