enum EventTypes {
  ACTIVATION_COMPLETE = 'ACTIVATION_COMPLETE',
  VIDEO_SEARCH = 'VIDEO_SEARCH',
  VIDEO_VISITED = 'VIDEO_VISITED',
  VIDEO_LINK_COPIED = 'VIDEO_LINK_COPIED',
  VIDEO_ADDED_TO_COLLECTION = 'COLLECTION_VIDEO_ADDED',
  VIDEO_REMOVED_FROM_COLLECTION = 'COLLECTION_VIDEO_REMOVED',
  DEFAULT_COLLECTION_VISITED = 'COLLECTION_VISITED',
  MY_COLLECTIONS_VISITED = 'MY_COLLECTIONS_VISITED',
  VIDEO_PLAYBACK = 'VIDEO_PLAYBACK',
}

export default EventTypes;
