export enum PlatformInteractionType {
  REMOTE_LEARNING_BANNER_CLICKED = 'REMOTE_LEARNING_BANNER_CLICKED',
  HELP_MENU_CLICKED = 'HELP_MENU_CLICKED',
  ONBOARDING_PAGE_1_STARTED = 'ONBOARDING_PAGE_1_STARTED',
  ONBOARDING_PAGE_2_STARTED = 'ONBOARDING_PAGE_2_STARTED',
  ONBOARDING_PAGE_3_STARTED = 'ONBOARDING_PAGE_3_STARTED',
  ONBOARDING_PAGE_4_STARTED = 'ONBOARDING_PAGE_4_STARTED',
}
