export enum PlatformInteractionType {
  HELP_MENU_CLICKED = 'HELP_MENU_CLICKED',
  DIGITAL_CITIZENSHIP_COLLECTION_OPENED = 'DIGITAL_CITIZENSHIP_COLLECTION_OPENED',
  ONBOARDING_PAGE_1_STARTED = 'ONBOARDING_PAGE_1_STARTED',
  ONBOARDING_PAGE_2_STARTED = 'ONBOARDING_PAGE_2_STARTED',
  ONBOARDING_PAGE_3_STARTED = 'ONBOARDING_PAGE_3_STARTED',
  ONBOARDING_PAGE_4_STARTED = 'ONBOARDING_PAGE_4_STARTED',
}
