export enum PlatformInteractionType {
  DIGITAL_CITIZENSHIP_COLLECTION_OPENED = 'DIGITAL_CITIZENSHIP_COLLECTION_OPENED',
  HELP_MENU_CLICKED = 'HELP_MENU_CLICKED',
  ONBOARDING_PAGE_1_STARTED = 'ONBOARDING_PAGE_1_STARTED',
  ONBOARDING_PAGE_2_STARTED = 'ONBOARDING_PAGE_2_STARTED',
  ONBOARDING_PAGE_3_STARTED = 'ONBOARDING_PAGE_3_STARTED',
  ONBOARDING_PAGE_4_STARTED = 'ONBOARDING_PAGE_4_STARTED',
  SHARE_CODE_MODAL_IMPRESSION = 'SHARE_CODE_MODAL_IMPRESSION',
  SHARE_CODE_MODAL_INVALID = 'SHARE_CODE_MODAL_INVALID',
  SHARE_CODE_MODAL_VALID = 'SHARE_CODE_MODAL_VALID',
}
