#!/usr/bin/env bash

set -e

unknown=0

if [ "$#" -eq 2 ] && [ "$2" = "ci" ]
then
    cypress="npm run cypress:run"
else
    cypress="npm run cypress:open"
fi

if [ "$#" -eq 0 ] || [ $unknown -eq 1 ]
then
    read -p "Which environment to run against? " env
else
    env=$1
fi

case $env in
    [Ll]* )
        CYPRESS_BASE_URL=http://localhost:3000 \
            $cypress
        ;;
    [Tt]* )
        CYPRESS_BASE_URL=https://educators.testing-boclips.com \
            $cypress
        ;;
    [Ss]* )
        CYPRESS_BASE_URL=https://educators.staging-boclips.com \
            $cypress
        ;;
    * )
        echo "Please answer [l]ocal, [t]esting or [s]taging."
        unknown=1
        ;;
esac
