apiVersion: apps/v1
kind: Deployment
metadata:
  name: teachers
  annotations:
    sidecar.jaegertracing.io/inject: jaeger
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: teachers
        image: app:1
        env:
        - name: SENTRY_RELEASE
          value: teachers-$(VERSION)
        ports:
        - name: http
          containerPort: 80
        envFrom:
        - secretRef:
            name: teachers
