apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
- www-redirect.yaml
commonLabels:
  app: teachers
commonAnnotations:
  boclips-version: "125"
images:
- name: app
  newName: eu.gcr.io/boclips-prod/boclips/teachers
  newTag: "125"
patches:
- path: pre-stop-nginx-spa.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
- path: spread-across-zones.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
- path: boot-time.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
- path: scale.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
vars:
- fieldref:
    fieldPath: metadata.annotations.boclips-version
  name: VERSION
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: teachers
- fieldref:
    fieldPath: spec.rules[0].host
  name: DOMAIN
  objref:
    apiVersion: extensions/v1beta1
    kind: Ingress
    name: teachers
